spring:
  application:
    name: service
  profiles:
    active: dev

server:
  port: 11002

mybatis:
  type-aliases-package: com.demo.service.**.model
  mapper-locations: classpath:sqlmap/**/*.xml
  base-package: com.demo.service.**.mapper

mapper:
  mappers:
     - tk.mybatis.mapper.common.Mapper
     - tk.mybatis.mapper.common.special.InsertListMapper
  not-empty: false
  identity: MYSQL

